apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-jq-executor
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XRegisterExample
  mode: Pipeline
  pipeline:
  - step: patch-and-transform-first-http-request
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: first-http-request
          base:
            apiVersion: http.crossplane.io/v1alpha2
            kind: DisposableRequest
            metadata:
              name: fake
            spec:
              deletionPolicy: Orphan
              forProvider:
                url: http://172.17.0.1:8000/api/v1/pet/fake
                method: GET
                rollbackRetriesLimit: 5
              providerConfigRef:
                name: http-conf
          patches:
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: spec.name
                strategy: string
                string:
                  fmt: "first-request-%s"
              toFieldPath: metadata.name
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: spec.name
                strategy: string
                string:
                  fmt: "http://172.17.0.1:8080/api/v1/pet/%s"
              toFieldPath: spec.forProvider.url
            - type: ToCompositeFieldPath
              fromFieldPath: status.response.body
              toFieldPath: status.data
  - step: execute-jsonQuery
    functionRef:
      name: function-jq-executor
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      jsonDataPath: status.data
      jsonQuery: ".id"
      responsePath: status.value
  - step: patch-and-transform-second-request
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: second-http-request
          base:
            apiVersion: http.crossplane.io/v1alpha2
            kind: DisposableRequest
            metadata:
              name: fake-second
            spec:
              deletionPolicy: Orphan
              forProvider:
                url: http://172.17.0.1:8000/api/v1/notify/fake
                method: GET
                rollbackRetriesLimit: 5
              providerConfigRef:
                name: http-conf
          patches:
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: spec.name
                strategy: string
                string:
                  fmt: "second-request-%s"
              toFieldPath: metadata.name
            - type: FromCompositeFieldPath
              fromFieldPath: status.value
              toFieldPath: metadata.labels["request-1-value"]
              policy:
                fromFieldPath: Required
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: status.value
                strategy: string
                string:
                  fmt: "http://172.17.0.1:8080/api/v1/notify/%s"
              toFieldPath: spec.forProvider.url
