apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xregisterexamples.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: XRegisterExample
    plural: xregisterexamples
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
            status:
              type: object
              properties:
                data:
                  type: string
                value:
                  type: string
      served: true
      referenceable: true