---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-jq-executor
spec:
  package: docker.io/marcosquesada/function-jq-executor:v0.0.6
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.1.4